version: '3.6'
services:
  dev:
    image: node:16
    user: "$UID:$GID"
    volumes:
      - ".:/home/user/declared"
      - "./bin/bashrc:/.bashrc"
    command: sleep infinity
    working_dir: /home/user/declared
  metadata:
    image: postgres:12
    restart: always
    volumes:
    - declared_metadata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  db:
    image: postgres:12
    restart: always
    volumes:
    - declared_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: hasura
  graphql-engine:
    image: hasura/graphql-engine:v2.0.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@metadata:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      DECLARED_DB_URL: postgres://hasura:password@db:5432
volumes:
  declared_metadata:
  declared_data:
