version: '3'
services:
  server:
    image: postgrest/postgrest:v5.1.0
    ports:
      - 3000
    environment:
      PGRST_DB_URI: postgres://user:password@db:5432/app
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: user
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    ports:
      - 5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
